//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XYZ.Dominio
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class TbCliente
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public string TelefoneResidencial { get; set; }
        public string Endereco { get; set; }
        public Nullable<System.DateTime> DataNascimento { get; set; }
        public string TelefoneCelular { get; set; }
    }
}
