//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Integracao.XYZServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TbCliente", Namespace="http://schemas.datacontract.org/2004/07/XYZ.Dominio")]
    [System.SerializableAttribute()]
    public partial class TbCliente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Nullable<System.DateTime> DataNascimentok__BackingFieldField;
        
        private string Enderecok__BackingFieldField;
        
        private int Idk__BackingFieldField;
        
        private string Nomek__BackingFieldField;
        
        private string TelefoneCelulark__BackingFieldField;
        
        private string TelefoneResidencialk__BackingFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<DataNascimento>k__BackingField", IsRequired=true)]
        public System.Nullable<System.DateTime> DataNascimentok__BackingField {
            get {
                return this.DataNascimentok__BackingFieldField;
            }
            set {
                if ((this.DataNascimentok__BackingFieldField.Equals(value) != true)) {
                    this.DataNascimentok__BackingFieldField = value;
                    this.RaisePropertyChanged("DataNascimentok__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Endereco>k__BackingField", IsRequired=true)]
        public string Enderecok__BackingField {
            get {
                return this.Enderecok__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Enderecok__BackingFieldField, value) != true)) {
                    this.Enderecok__BackingFieldField = value;
                    this.RaisePropertyChanged("Enderecok__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Id>k__BackingField", IsRequired=true)]
        public int Idk__BackingField {
            get {
                return this.Idk__BackingFieldField;
            }
            set {
                if ((this.Idk__BackingFieldField.Equals(value) != true)) {
                    this.Idk__BackingFieldField = value;
                    this.RaisePropertyChanged("Idk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Nome>k__BackingField", IsRequired=true)]
        public string Nomek__BackingField {
            get {
                return this.Nomek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Nomek__BackingFieldField, value) != true)) {
                    this.Nomek__BackingFieldField = value;
                    this.RaisePropertyChanged("Nomek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<TelefoneCelular>k__BackingField", IsRequired=true)]
        public string TelefoneCelulark__BackingField {
            get {
                return this.TelefoneCelulark__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefoneCelulark__BackingFieldField, value) != true)) {
                    this.TelefoneCelulark__BackingFieldField = value;
                    this.RaisePropertyChanged("TelefoneCelulark__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<TelefoneResidencial>k__BackingField", IsRequired=true)]
        public string TelefoneResidencialk__BackingField {
            get {
                return this.TelefoneResidencialk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefoneResidencialk__BackingFieldField, value) != true)) {
                    this.TelefoneResidencialk__BackingFieldField = value;
                    this.RaisePropertyChanged("TelefoneResidencialk__BackingField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BusinessFault", Namespace="http://schemas.datacontract.org/2004/07/XYZ.WcfIntegracao.Faults")]
    [System.SerializableAttribute()]
    public partial class BusinessFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensagemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensagemInternaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StackTraceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TituloField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensagem {
            get {
                return this.MensagemField;
            }
            set {
                if ((object.ReferenceEquals(this.MensagemField, value) != true)) {
                    this.MensagemField = value;
                    this.RaisePropertyChanged("Mensagem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MensagemInterna {
            get {
                return this.MensagemInternaField;
            }
            set {
                if ((object.ReferenceEquals(this.MensagemInternaField, value) != true)) {
                    this.MensagemInternaField = value;
                    this.RaisePropertyChanged("MensagemInterna");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StackTrace {
            get {
                return this.StackTraceField;
            }
            set {
                if ((object.ReferenceEquals(this.StackTraceField, value) != true)) {
                    this.StackTraceField = value;
                    this.RaisePropertyChanged("StackTrace");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Titulo {
            get {
                return this.TituloField;
            }
            set {
                if ((object.ReferenceEquals(this.TituloField, value) != true)) {
                    this.TituloField = value;
                    this.RaisePropertyChanged("Titulo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="XYZServiceReference.IIntegracaoService")]
    public interface IIntegracaoService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntegracaoService/ObterClientesIncompletos", ReplyAction="http://tempuri.org/IIntegracaoService/ObterClientesIncompletosResponse")]
        Integracao.XYZServiceReference.TbCliente[] ObterClientesIncompletos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntegracaoService/ObterClientesIncompletos", ReplyAction="http://tempuri.org/IIntegracaoService/ObterClientesIncompletosResponse")]
        System.Threading.Tasks.Task<Integracao.XYZServiceReference.TbCliente[]> ObterClientesIncompletosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntegracaoService/ObterClientePorId", ReplyAction="http://tempuri.org/IIntegracaoService/ObterClientePorIdResponse")]
        Integracao.XYZServiceReference.TbCliente ObterClientePorId(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntegracaoService/ObterClientePorId", ReplyAction="http://tempuri.org/IIntegracaoService/ObterClientePorIdResponse")]
        System.Threading.Tasks.Task<Integracao.XYZServiceReference.TbCliente> ObterClientePorIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntegracaoService/AtualizarCliente", ReplyAction="http://tempuri.org/IIntegracaoService/AtualizarClienteResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Integracao.XYZServiceReference.BusinessFault), Action="http://tempuri.org/IIntegracaoService/AtualizarClienteBusinessFaultFault", Name="BusinessFault", Namespace="http://schemas.datacontract.org/2004/07/XYZ.WcfIntegracao.Faults")]
        void AtualizarCliente(Integracao.XYZServiceReference.TbCliente cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntegracaoService/AtualizarCliente", ReplyAction="http://tempuri.org/IIntegracaoService/AtualizarClienteResponse")]
        System.Threading.Tasks.Task AtualizarClienteAsync(Integracao.XYZServiceReference.TbCliente cliente);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IIntegracaoServiceChannel : Integracao.XYZServiceReference.IIntegracaoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IntegracaoServiceClient : System.ServiceModel.ClientBase<Integracao.XYZServiceReference.IIntegracaoService>, Integracao.XYZServiceReference.IIntegracaoService {
        
        public IntegracaoServiceClient() {
        }
        
        public IntegracaoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IntegracaoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IntegracaoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IntegracaoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Integracao.XYZServiceReference.TbCliente[] ObterClientesIncompletos() {
            return base.Channel.ObterClientesIncompletos();
        }
        
        public System.Threading.Tasks.Task<Integracao.XYZServiceReference.TbCliente[]> ObterClientesIncompletosAsync() {
            return base.Channel.ObterClientesIncompletosAsync();
        }
        
        public Integracao.XYZServiceReference.TbCliente ObterClientePorId(int id) {
            return base.Channel.ObterClientePorId(id);
        }
        
        public System.Threading.Tasks.Task<Integracao.XYZServiceReference.TbCliente> ObterClientePorIdAsync(int id) {
            return base.Channel.ObterClientePorIdAsync(id);
        }
        
        public void AtualizarCliente(Integracao.XYZServiceReference.TbCliente cliente) {
            base.Channel.AtualizarCliente(cliente);
        }
        
        public System.Threading.Tasks.Task AtualizarClienteAsync(Integracao.XYZServiceReference.TbCliente cliente) {
            return base.Channel.AtualizarClienteAsync(cliente);
        }
    }
}
